version: "3.7" # 这个是配置文件的版本，不同的版本号声明方式会有细微的不同
services:
    info:
        container_name: test
        image: christine2591/test:latest
        ports:
            - "2333:80"
        restart: on-failure